spring.application.name=movie-watchlist

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/movie-watchlist-db
spring.datasource.username=day
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# OMDb API Configuration
omdb.api.base-url=https://omdbapi.com
omdb.api.key=${OMDB_API_KEY}

# JWT Configuration
security.jwt.secret-key=dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleTExMjM0NTY=
security.jwt.expiration-time=3600000