spring.application.name=movie-watchlist

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/movie-watchlist-db
spring.datasource.username=day
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# OMDb API Configuration
omdb.api.base-url=https://omdbapi.com
omdb.api.key=${OMDB_API_KEY}