spring.application.name=movie-watchlist

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/movie-watchlist-db
spring.datasource.username=day
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# OMDb API Configuration
omdb.api.base-url=https://omdbapi.com
omdb.api.key=${OMDB_API_KEY}

# JWT Configuration
// should be an environment variable, but for testing purposes, we can set it here
security.jwt.secret-key=Y2E5ZTFkMzRiOGE5YjYyMDFlYzg0M2U5MmFmNzM1YjY4YzFkZDUwMmU0YTM4YTk2YmU4YzhkMmI0MmU0MzgxYg==
security.jwt.expiration-time=3600000